## A lot of this is copied and slightly modified from hyphy_analyses.9.sh
## But this is called by that script
## (as noted in that script) to deal with the MSAs that MACSE gave ! marks


## Get variables
print_usage() {
  printf "usage requires:\n\
main_dir -m\n\
ingroup_prefix_list -I\n\
outgroup_prefix_list -O\
"
}

while getopts 'm:I:O:' flag; do
  case "${flag}" in
    m) main_dir="${OPTARG}" ;;
    I) ingroup_prefix_list="${OPTARG}" ;;
    O) outgroup_prefix_list="${OPTARG}" ;;
    *) print_usage
       exit 1 ;;
  esac
done


#######################
## Exclamation marks ##
#######################

## Better to use the msas that have already been modified (for instance removing the stop codons)
cd ${main_dir}/hyphy_out/msas
## Will just remake the list in case the list of hogs with !s that was generated by the hyphy RELAX loop got messed up during the parall>
## I checked and the output is identical, so the loop worked fine.
grep "!" *.noStop.fa | sed 's/.noStop.fa.*//' | sort -u > msas_with_exclamation_marks.list
## Check if any of these look like important genes in the annotations
#> exclamation_annotations.tsv
#cat msas_with_exclamation_marks.list | \
#while read hog; do
#echo $hog >> exclamation_annotations.tsv
#cat /home/liam/data/main_pipeline/annotations/eggnog-mapper_out/hog_annotations/${hog}_annotations.tsv >> exclamation_annotations.tsv
#done
## Lots of well-annotated hogs in this group

## Remove !-containing seqs from fna and ffa 's
mkdir msas_with_exclamation_marks_removed
cat msas_with_exclamation_marks.list | \
while read hog; do
grep --no-group-separator -B1 "!" ${hog}.noStop.fa | grep "^>" | sed 's/^>//' > prefixes2remove.tmp
grep --no-group-separator -vFf prefixes2remove.tmp ~/subtree.prefix.list > prefixes2keep.tmp
grep --no-group-separator -A1 -Ff prefixes2keep.tmp ${hog}.noStop.fa > msas_with_exclamation_marks_removed/${hog}.noStop.fa
done
rm prefixes2remove.tmp prefixes2keep.tmp

## Check which !-deleted HOGs could pass the 75% threshold
#cd msas_with_exclamation_marks_removed
#> hog_presence_portions.tsv
#cat ../msas_with_exclamation_marks.list | \
#while read hog; do
#cat ${hog}.noStop.fa | \
#grep "^>" | \
#sed 's/^>//' \
#> tmp
#ingroup_p=$(grep -c -Ff $ingroup_prefix_list tmp)
#outgroup_p=$(grep -c -Ff $outgroup_prefix_list tmp)
#echo -e "${hog}\t${ingroup_p}\t${outgroup_p}" >> hog_presence_portions.tsv
#rm tmp
#done
#ingroup_n=$( wc -l < $ingroup_prefix_list )
#outgroup_n=$( wc -l < $outgroup_prefix_list )
#cat hog_presence_portions.tsv | awk -v i_n=$ingroup_n -v o_n=$outgroup_n '$2>=0.75*i_n && $3>=0.75*o_n {print $1}' > hogs_passed_75_thresh.list
#wc -l hogs_passed_75_thresh.list
## 57 out of 64 (main_pipeline)
## 50 out of 50 (cylindro pipeline)
## Look at the hogs that do not pass the threshold
#grep -vFf hogs_passed_75_thresh.list ../msas_with_exclamation_marks.list > hogs_not_passed_75_thresh.list
## These 7 do have reasonably interesting annotations, including a cytochrome (main_pipeline)
## 5 / 7 have 5 T. az. present (main_pipeline)

## Check which !-deleted HOGs could pass the 3-in-each-group threshold
cd msas_with_exclamation_marks_removed
> hog_presence_portions.tsv
cat ../msas_with_exclamation_marks.list | \
while read hog; do
cat ${hog}.noStop.fa | \
grep "^>" | \
sed 's/^>//' \
> tmp
ingroup_n=$(grep -c -Ff $ingroup_prefix_list tmp)
outgroup_n=$(grep -c -Ff $outgroup_prefix_list tmp)
echo -e "${hog}\t${ingroup_n}\t${outgroup_n}" >> hog_presence_portions.tsv
rm tmp
done
cat hog_presence_portions.tsv | awk '$2>=3 && $3>=3 {print $1}' > hogs_passed_3_thresh.list
wc -l ../msas_with_exclamation_marks.list
wc -l hogs_passed_3_thresh.list
## 57 out of 64 (main_pipeline)
## 54 out of 55 (cylindro pipeline) 110 out of 124 (Nos pipeline) 78 out of 80 (DolAna pipeline)
## Look at the hogs that do not pass the threshold
grep -vFf hogs_passed_3_thresh.list ../msas_with_exclamation_marks.list > hogs_not_passed_3_thresh.list
## These 7 do have reasonably interesting annotations, including a cytochrome (main_pipeline)
## 5 / 7 have 5 T. az. present (main_pipeline)




##########################
#### Prune gene trees ####
##########################

msa_dir=${main_dir}/hyphy_out/msas/msas_with_exclamation_marks_removed
in_tree=/home/liam/data/main_pipeline/orthofinder_out/final_run/Species_Tree/SpeciesTree_rooted_node_labels.txt
tree_outdir=${main_dir}/hyphy_out/trees
logfile=gotree_prune.log
cd $tree_outdir
conda deactivate
conda activate gotree
## Loop through each HOG (so each line in loci2keep)
## Start at line 2 to skip header
# > $logfile #already exists from gotree prune on the non-!-containing msas
cat ${msa_dir}/hogs_passed_3_thresh.list | \
while read hog; do
msa_file=${msa_dir}/${hog}.noStop.fa
echo $hog >> $logfile
#Get the list of species to be kept by gotree prune.
grep "^>" $msa_file | sed 's/^>//' > species2keep.tmp 
##Prune the corresponding gene tree using gotree
gotree prune -r -i $in_tree -f species2keep.tmp -o ./${hog}.pruned_tree.txt >> $logfile
done
rm *.tmp
echo "Were there any errors from prune tree? (print empty if no):"
if ! grep -q -v "^N9" $logfile; then rm $logfile; else grep -v "^N9" $logfile; fi


###################
### Label trees ###
###################

## Label test, reference nodes on trees for BUSTED and RELAX hyphy analyses.
## All nodes that contain exclusively T. az. are test except the root of the T. az. zlade which is unlabeled
## All other nodes are labeled reference
## https://github.com/veg/hyphy-analyses/tree/master/LabelTrees
conda deactivate
indir=${main_dir}/hyphy_out/trees
cd $indir

## Label!
logfile=label-tree.log
echo "label single copy gene trees" > $logfile
cat ${msa_dir}/hogs_passed_3_thresh.list | \
while read hog; do
in_tree=${hog}.pruned_tree.txt
out_tree=${hog}.labeled_tree.txt
echo "$hog" >> $logfile
## Get list of species in this hog.
bash -i /home/liam/scripts/helper/label_trees_not_ingroup_root.sh -i $in_tree -o $out_tree -l $logfile\
 -I ${ingroup_prefix_list} -O ${outgroup_prefix_list}
done

## Check one set of erros from helper script
ls *pruned_tree.txt | wc -l
grep --no-group-separator -A1 "Are descendent nodes always before ancestor nodes?" $logfile | grep -v "^Are" | sort | uniq -c
## All yes
## Get the no HOGs
grep -B2 --no-group-separator "^No!" $logfile | awk 'NR %3==1'
## Empty
## logfile looks good
rm $logfile *.pruned_tree.txt


#################
### Run RELAX ###
#################

conda deactivate
msa_dir=${main_dir}/hyphy_out/msas/msas_with_exclamation_marks_removed
tree_dir=${main_dir}/hyphy_out/trees
outdir=${main_dir}/hyphy_out/relax_out
cd $outdir
cat ${msa_dir}/hogs_passed_3_thresh.list | \
## subset for parallelization
#awk 'NR%4==0' | \
while read hog; do
tree_file=${tree_dir}/${hog}.labeled_tree.txt
msa_file=${msa_dir}/${hog}.noStop.fa
outfile=${hog}.relax_out.json
stdoutfile=${hog}.relax_out.txt
hyphy relax --alignment $msa_file --tree $tree_file --test "test" --reference "reference"\
 --models Minimal --srv Yes --output $outfile > $stdoutfile
done

#########################
## Deal with HOGs that ##
#### did not converge ###
#########################

> exclamation_unconverged_HOGs.list
> exclamation_converged_HOGs.list
cat ${msa_dir}/hogs_passed_3_thresh.list | \
while read hog; do
file=${hog}.relax_out.txt
#Take the last line with text on it
cat $file | sed '/^$/d' | tail -n 1 > tmp
#Check if the last line has a message about convergence
if grep -q "converge" tmp; then echo $file >> exclamation_unconverged_HOGs.list; fi
##Check that the other files all end as I expect
if grep -q "^----" tmp; then echo $file >> exclamation_converged_HOGs.list; fi
done
rm tmp

echo "Check for error messages:"
grep -i "error" *.txt
##Check that I got all files with those two greps
wc -l exclamation_unconverged_HOGs.list
# 0
wc -l exclamation_converged_HOGs.list 
# 82
# 82 = 82 + 0
# Success.
# Everything converged! No need to run hyphy again!
cat exclamation_converged_HOGs.list >> successfully_run_HOGs.list
cat exclamation_unconverged_HOGs.list >> unconverged_HOGs.list
rm exclamation_converged_HOGs.list exclamation_unconverged_HOGs.list
