##Use mmseqs2 taxonomy module to assign taxonomy to the contigs generated by assembly_pipeline.sh
##Use bwa mem to align previously trimmed and filtered (against reference plant nuclear and chloroplast genome)
##To the contigs assigned "Streptophyta".
##Remove those reads
##Reassemble and bin.
##use mmseqs2 taxonomy on the new bins and on unbinned contigs
##Curate the T. az. bins manually


###############################################
## Filter out reads before a second assembly ##
###############################################

##Run mmseqs taxonomy on every contig from every Li re-assembly.
##These will be used to identify streptophyta (plant) contigs
##Which reads will then be aligned and filtered against before a final assembly and binning.
mkdir ~/data/mmseqs2_out/all_contigs
cd ~/data/mmseqs2_out/all_contigs

##Combine all contigs with len >= 2500 from the metaSPAdes assemblies into one file
##add the name of the assembly to the start of each contig header so can separate out after.
outfile=allAssemblies.allContigs.fa
> $outfile
##The following works because spades orders the contigs by length (descending) in scaffolds.fasta
cat ~/Li.prefix.list | \
while read prefix; do
cat ~/data/assembly_workflow/metaSPAdes/assemblies/${prefix}/scaffolds.fasta | \
awk -F "_" '$0 ~ "^>" && $4 < 2500 {exit}; {print $0}' | \
sed "s/^>/>${prefix}_/" \
>> $outfile
done


##Run mmseqs taxonomy
conda deactivate
conda activate mmseqs2
query=$outfile
queryDB=${query}.DB
seqTaxDB=~/data/mmseqs2_out/nr_for_mmseqs2/nr_for_mmseqs2
mmseqs createdb $query $queryDB
mmseqs taxonomy --lca-ranks species --split-memory-limit 140G $queryDB $seqTaxDB taxonomyResult tmp
mmseqs createtsv $queryDB taxonomyResult taxonomyResult.tsv
sort -t $'\t' -k1,1 taxonomyResult.tsv > taxonomyResult.sorted.tsv
awk -F "\t" '$9 == "Streptophyta" {print $0}' taxonomyResult.sorted.tsv > streptophyta.tsv
mmseqs taxonomyreport $seqTaxDB taxonomyResult taxonomyResult_report

##Get a list of streptophyta contigs for each MAG.
awk -F "\t" '{print $1}' streptophyta.tsv > streptophyta.contigs.list
cat ~/Li.prefix.list | \
while read prefix; do
cat streptophyta.contigs.list | \
awk -v prefix=$prefix -F "_" '$1 == prefix {for (i=2; i<NF; i++) {printf $i"_"}; print $NF}' > ${prefix}.streptophyta.contigs.list
done

##Move mmseqs outdir
cd ~/data
mv mmseqs2_out/ assembly_workflow/




echo "\
######################################\n\
### Align and filter reads! ##########\n\
######################################\
"


####SCREEN!###
conda deactivate
conda activate samtools

mkdir ~/data/assembly_workflow/streptophyta_reads
mkdir ~/data/assembly_workflow/metaSPAdes/reassemblies

cat ~/Li.prefix.list | \
while read prefix; do

mkdir ~/data/assembly_workflow/streptophyta_reads/${prefix}
cd ~/data/assembly_workflow/streptophyta_reads/${prefix}


##Create a fasta of the contigs to be filtered against
contig_list=~/data/assembly_workflow/mmseqs2_out/all_contigs/${prefix}.streptophyta.contigs.list
cat ~/data/assembly_workflow/metaSPAdes/assemblies/${prefix}/scaffolds.fasta | \
awk ' {if ($0 ~ "^>") {printf "\n"$0"\n"} else { printf $0} }; END {printf "\n"} ' | \
tail -n +2 \
> scaffolds_unwrapped.fasta.tmp
grep --no-group-separator -A1 -Ff $contig_list scaffolds_unwrapped.fasta.tmp > streptophyta.contigs.fasta

##Align reads
reference=~/data/assembly_workflow/streptophyta_reads/${prefix}/streptophyta.contigs.fasta
outdir=~/data/assembly_workflow/streptophyta_reads/${prefix}
indir=~/data/assembly_workflow/trimmomatic_out/${prefix}
bwa index $reference
##I could re-write this so that the paired reads are done together.
##But I think it doesn't matter if I am only using reads where neither partner mapped.
for infile in ${indir}/*.fq; do
suffix=${infile##*_}
suffix=${suffix%.fq}
bwa mem $reference $infile > $outdir/filteredReads2streptophyta_${suffix}.sam
done
#Filter out paired reads that are unmapped and partner is unmapped
#and unpaired reads that are unmapped.
## samtools view -f 4 is equivalent to awk ' ($2 % 8) >= 4 {print $0}'
## samtools view -f 4,8 is equivalent to awk ' ($2 % 16) >= 12 {print $0}'
## The first prints all unmapped reads.
## The second prints all reads where both read and partner are unmapped.
## If doing this with paired reads, samtools view -f 4,8 could be used instead of the awk call.
## See code notes from Jan 26.
##The @ symbol before and space after $1 in awk is to make grep -Ff work better.
cd $outdir
for infile in filteredReads2streptophyta_*.sam; do
echo $infile
suffix=${infile#filteredReads2streptophyta_}
suffix=${suffix%.sam}
echo $suffix
cat $infile | awk ' ($2 % 8) >= 4 {print "@"$1" "}' > Unmapped_${suffix}.list
done && \
##gzip the original sam files now that no longer needed.
pigz --best filteredReads2streptophyta_*.sam

##If ran 1P and 2P separate, remove reads that did not hit both:
#Something in this pipe erases the space at the end of the line
#So I add it back in the awk call
cat Unmapped_1P.list Unmapped_2P.list | \
sort | uniq -c | awk '$1 == 2 {print $2" "}' \
> both_unmapped.list
##make fastqs of only the double-filtered hits.
cd ~/data/assembly_workflow/streptophyta_reads/${prefix}
indir=~/data/assembly_workflow/trimmomatic_out/${prefix}
grep --no-group-separator -A3 -Ff both_unmapped.list ${indir}/filtered_1P.fq > ${indir}/double_filtered_1P.fq && \
grep --no-group-separator -A3 -Ff both_unmapped.list ${indir}/filtered_2P.fq > ${indir}/double_filtered_2P.fq && \
grep --no-group-separator -A3 -Ff Unmapped_1U.list ${indir}/filtered_1U.fq > ${indir}/double_filtered_1U.fq && \
grep --no-group-separator -A3 -Ff Unmapped_2U.list ${indir}/filtered_2U.fq > ${indir}/double_filtered_2U.fq && \
pigz --best ${indir}/filtered*.fq


####Assemble!
echo -e "\
######################################\n\
### Assemble! ########################\n\
######################################\
"
indir=~/data/assembly_workflow/trimmomatic_out/${prefix}
cd ~/data/assembly_workflow/metaSPAdes/reassemblies
conda deactivate
conda activate spades
~/miniconda3/envs/spades/bin/spades.py --meta -o $prefix -1 ${indir}/double_filtered_1P.fq -2 ${indir}/double_filtered_2P.fq -s ${indir}/double_filtered_1U.fq -s ${indir}/double_filtered_2U.fq

done


##Do some re-organizing of directories!
cd ~/data/assembly_workflow
mv ~/data/SRA_files/ ./
mv trimmomatic_out trimmed_and_filtered_reads
mv streptophyta_reads filter_streptophyta_reads
mv filter_PlantChlpReads filter_plant_nuc_chlp_reads
mkdir other_assemblers
mv megahit/ other_assemblers/
mv SPAdes/ other_assemblers/
mv metaSPAdes/metabat2_out/ ./
mv metaSPAdes/assemblies metaSPAdes/first_assemblies
mv metaSPAdes/reassemblies/ metaSPAdes/second_assemblies
cd metabat2_out/
mkdir first_assemblies
cat ~/Li.prefix.list | \
while read prefix; do
echo $prefix
mv $prefix first_assemblies
done
mkdir second_assemblies

#########
###BIN###
#########
cat ~/Li.prefix.list | \
while read prefix; do
echo $prefix

##Align reads to assembly before binning!
#Set variables
echo -e "\
######################################\n\
### Align before binning! ############\n\
######################################\
"
outdir=~/data/assembly_workflow/metabat2_out/second_assemblies/${prefix}
mkdir $outdir
cd $outdir
outfile=${prefix}.pairedReads2assembly.sam
reads_dir=~/data/assembly_workflow/trimmed_and_filtered_reads/${prefix}
reads_1=double_filtered_1P.fq
reads_2=double_filtered_2P.fq
subject=~/data/assembly_workflow/metaSPAdes/second_assemblies/${prefix}/scaffolds.fasta
# run bwa mem
conda deactivate
conda activate samtools
bwa index $subject
bwa mem -t 20 $subject ${reads_dir}/${reads_1} ${reads_dir}/${reads_2} > ${outdir}/${outfile}
#convert sam to bam file, sort BAM and create an index
cd $outdir
samtools view -b -o ${prefix}.pairedReads2assembly.bam -S ${prefix}.pairedReads2assembly.sam && \
samtools sort ${prefix}.pairedReads2assembly.bam -o ${prefix}.pairedReads2assembly.sorted.bam && \
samtools index ${prefix}.pairedReads2assembly.sorted.bam


##Bin!!!
##Get depth file with metabat2
echo -e "\
######################################\n\
############### Bin! #################\n\
######################################\
"
conda deactivate
conda activate metabat2
cd $outdir
infile=${prefix}.pairedReads2assembly.sorted.bam
jgi_summarize_bam_contig_depths --outputDepth ${prefix}.metabat2.depth.txt $infile
#run metabat2
assembly=$subject
depth_file=${prefix}.metabat2.depth.txt
metabat2 -i $assembly -a $depth_file -o ${prefix}
#calculate GC content for metabat2 bins
echo -e "bin\ngenomeSize\nGC%" > GC_content.tsv
for file in *.fa; do
echo $file;
cat $file | grep -v "^>" > tmp.tmp
n_char=$((60*$(cat tmp.tmp | wc -l)));
echo -e "${file%.fa}\n$n_char" >> GC_content.tsv
n_GC=$(cat tmp.tmp | tr -cd 'GC' | wc -c)
awk -v n_GC=$n_GC -v n_char=$n_char 'BEGIN {print n_GC/n_char}' >> GC_content.tsv
rm tmp.tmp
done
cat GC_content.tsv | \
awk -F "\n" 'NR % 3 == 0 {print $0; next}; {printf $0"\t"}' | \
sort -t $'\t' -k3,3 -n > tmp.tmp
mv tmp.tmp GC_content.tsv
#Blast bins against reference genome to find plasmids and chromosomes.
conda deactivate
db_dir=~/data/reference
echo -e "Taz_chrom.ffn\nTaz_plas1.ffn\nTaz_plas2.ffn" > db.list.tmp
cat db.list.tmp | \
while read db; do
#makeblastdb -in $db_dir/$db -dbtype nucl 
for file in *.fa; do 
bin=${file##*/}
echo $bin;
outfile=${bin%.fa}.${db%.ffn}.blastout.tsv;
query=$file
blastn -query $query -db ${db_dir}/${db} -outfmt 6 -out $outfile;
done;
done
rm *.tmp
echo "n_contigs" > n_contigs.col.tmp
echo "n_contigs_chrom" > chrom.col.tmp
echo "n_contigs_plas1" > plas1.col.tmp
echo "n_contigs_plas2" > plas2.col.tmp

tail -n +2 GC_content.tsv | awk '{print $1}' | \
while read bin; do
echo $bin;
file=${bin}.fa
grep -c "^>" $file >> n_contigs.col.tmp
cat ${bin}.Taz_chrom.blastout.tsv | awk '{print $1}' | sort -u | wc -l >> chrom.col.tmp
cat ${bin}.Taz_plas1.blastout.tsv | awk '{print $1}' | sort -u | wc -l >> plas1.col.tmp
cat ${bin}.Taz_plas2.blastout.tsv | awk '{print $1}' | sort -u | wc -l >> plas2.col.tmp
done
paste GC_content.tsv n_contigs.col.tmp chrom.col.tmp plas1.col.tmp plas2.col.tmp > bin_analysis.tsv
rm GC_content.tsv n_contigs.col.tmp chrom.col.tmp plas1.col.tmp plas2.col.tmp
##Get rid of all the empty blast files
for file in *blastout.tsv; do
if (( $(wc -l < $file) == 0 )); then
rm $file
fi
done

#blast all of the unbinned contigs with len >=2000
#remove contigs with len < 2500
#This is the default for metabat2

assembly=~/data/assembly_workflow/metaSPAdes/second_assemblies/${prefix}/scaffolds.fasta
outdir=~/data/assembly_workflow/metabat2_out/second_assemblies/${prefix}
#remove contigs with len < 2500
#This is the default for metabat2
cd $outdir
cp $assembly ./
#This works because SPAdes organizes the contigs from longest to shortest
awk -F "_" '$0 ~ "^>" && $4 < 2500 {exit}; {print $0}' scaffolds.fasta > contigs_longer_than_2500.fa
rm scaffolds.fasta
#unwrap to just one line per read (so not the normal 2-line unwrap)
cat contigs_longer_than_2500.fa | \
awk ' {if ($0 ~ "^>") {printf "\n"$0"\t"} else { printf $0} }; END {printf "\n"} ' | \
tail -n +2 \
> ${prefix}.unbinned.unwrapped.tmp
#list binned contigs
> binned_contigs.tmp
ls ${prefix}.[0-9]*.fa | \
while read file; do
echo $file;
grep "^>" $file >> binned_contigs.tmp
done
##Remove binned contigs
grep -v -Ff binned_contigs.tmp ${prefix}.unbinned.unwrapped.tmp > tmp.tmp
##Put into normal 2-line unwrapped
sed 's/\t/\n/g' tmp.tmp > ${prefix}.unbinned.fa
outfile=unbinned_contigs.Taz_complete.blastout.tsv;
db=~/data/reference/Taz_complete.ffn
query=${prefix}.unbinned.fa
blastn -query $query -db ${db} -outfmt 6 -out $outfile;
#look at hits with len >= 1000
awk '$4 > 1000 {print $0}' $outfile > unbinned_contigs.Taz_complete.minlen1K.blastout.tsv
rm *.tmp

done



##########################################
#### Taxonomy for manual bin curation ####
##########################################

##Code not shown:
##All bins that were assigned via my blast table above (bin_analysis.tsv in metabat2_out/$prefix/)
##Are combined if necessary to give a single fasta for each MAG.
##These are scp'ed to a local machine and submitted to checkM on kbase.us to predict completeness and contamination.
##Any other bins that hit T. az. in bin_analysis.tsv, I looked at those blast hits. All were len<100 so insignificant.

##Run mmseqs taxonomy on every contig from every Li re-assembly.
##These will be used to help manually add or remove contigs to/from bins
cd ~/data/assembly_workflow/mmseqs2_out
mkdir first_assemblies
mv all_assemblies first_assemblies
mv all_contigs first_assemblies
mkdir second_assemblies
cd second_assemblies
mkdir all_contigs
cd all_contigs

##Combine all contigs with len >= 2500 from the metaSPAdes assemblies into one file
##add the name of the assembly to the start of each contig header so can separate out after.
outfile=allAssemblies.allContigs.fa
> $outfile
cat ~/Li.prefix.list | \
while read prefix; do
cat ~/data/assembly_workflow/metabat2_out/second_assemblies/${prefix}/contigs_longer_than_2500.fa | \
sed "s/^>/>${prefix}_/" \
>> $outfile
done

##Run mmseqs taxonomy
conda deactivate
conda activate mmseqs2
query=allAssemblies.allContigs.fa
queryDB=${query}.DB
seqTaxDB=~/data/assembly_workflow/mmseqs2_out/nr_for_mmseqs2/nr_for_mmseqs2
mmseqs createdb $query $queryDB
mmseqs taxonomy --lca-ranks species --split-memory-limit 140G $queryDB $seqTaxDB taxonomyResult tmp
mmseqs createtsv $queryDB taxonomyResult taxonomyResult.tsv
sort -t $'\t' -k1,1 taxonomyResult.tsv > taxonomyResult.sorted.tsv

##Run mmseqs taxonomy on all of the bins from all of the second assemblies of the re-assembled Li MAGs
##Within each bin, all contigs are combined into a single sequence (single >header)
##With a run of 300 N's in between contigs.
cd ~/data/assembly_workflow/mmseqs2_out/second_assemblies
mkdir all_assemblies
cd all_assemblies

##Combine all the bins from all the meta-assemblies into one file for mmseqs taxonomy. For each bin, combine all contigs into a single sequence, with different contigs separated by runs of 300 N's.
##Note that for some of the meta-assemblies, there are bins that look no bueno in terms of being way too large.
##Note that this sed call leaves the line before the new contig as potentially shorter than full line length. I don't think this should matter.

outfile=allAssemblies.allBins.fa
> $outfile

##Add the bins as single sequences with contigs within each bin separated by a run of 300 N's
indir=~/data/assembly_workflow/metabat2_out/second_assemblies
cat ~/Li.prefix.list | \
while read prefix; do
ls ${indir}/${prefix}/${prefix}.[0-9]*.fa | \
while read file; do
bin=${file%.fa}
bin=${bin##*/}
echo ">${bin}" >> $outfile
tail -n +2 $file | \
sed "s/>.*$/$(printf '%.0sN' {1..60})\n$(printf '%.0sN' {1..60})\n$(printf '%.0sN' {1..60})\n$(printf '%.0sN' {1..60})\n$(printf '%.0sN' {1..60})\n$(printf '%.0sN' {1..60})/" \
>> $outfile
done
done
##Add the individual contigs which will help manual curation.
##These were also already done with the contigs above, but I did it twice due to a bug and some confusion.
##It could also maybe be done more smoothly with the mmseqs aggregatetax module
cat ~/Li.prefix.list | \
while read prefix; do
ls ${indir}/${prefix}/${prefix}.[0-9]*.fa | \
while read file; do
bin=${file%.fa}
bin=${bin##*/}
cat $file | \
sed "s/^>/>${prefix}_/" \
>> $outfile
done
done

##Done creating combined fasta input for mmseqs taxonomy module.

##Run mmseqs taxonomy
query=allAssemblies.allBins.fa
queryDB=${query}.DB
seqTaxDB=~/data/assembly_workflow/mmseqs2_out/nr_for_mmseqs2/nr_for_mmseqs2
mmseqs createdb $query $queryDB
mmseqs taxonomy $queryDB $seqTaxDB taxonomyResult tmp
mmseqs createtsv $queryDB taxonomyResult taxonomyResult.tsv
sort -t $'\t' -k1,1 taxonomyResult.tsv > taxonomyResult.sorted.tsv
##Split the contigs and bins
grep -v "NODE" taxonomyResult.sorted.tsv > bins.taxonomyResult.sorted.tsv
grep "NODE" taxonomyResult.sorted.tsv > contigs.taxonomyResult.sorted.tsv
rm taxonomyResult.sorted.tsv


##########################################
########## Manual bin curation ###########
##########################################


##Pull out only the unbinned contigs from the contig-level mmseqs taxonomy outputs.
cd ~/data/assembly_workflow/mmseqs2_out/second_assemblies/all_contigs
contig_list=unbinned_contig.list
bin_dir=~/data/assembly_workflow/metabat2_out/second_assemblies
> $contig_list
cat ~/Li.prefix.list | \
while read prefix; do
file=${bin_dir}/${prefix}/${prefix}.unbinned.fa
grep "^>" $file | \
sed "s/^>/${prefix}_/" \
>> $contig_list
done
grep -Ff $contig_list taxonomyResult.sorted.tsv > taxonomyResult.sorted.unbinned.tsv



##Get the total length of unbinned contigs assigned taxonomy T. az. by mmseqs taxonomy
##For each MAG
cat ~/Li.prefix.list | \
while read prefix; do 
echo $prefix; 
awk -F "\t" '$3=="species" && $4=="Trichormus azollae" {print $1}' taxonomyResult.sorted.unbinned.tsv | \
grep "^${prefix}" | \
awk -F "_" 'BEGIN {c=0}; {c+=$5}; END {print c}'; 
done

##Get the unbinned contigs that mmseqs taxonomy called Trichormus azollae with high confidence
awk -F "\t" '$3=="species" && $4=="Trichormus azollae" {print $0}' taxonomyResult.sorted.unbinned.tsv > taxonomyResult.sorted.unbinned.Taz.tsv


##Figure out the coverage depth range for the Taz bins
cd ~/data/assembly_workflow/metabat2_out/second_assemblies
##Create nano TazBins.tsv with first col prefix and 2nd col csv of bin numbers
outfile=depth_ranges.list
> $outfile
cat TazBins.tsv | \
while read prefix csv; do
echo $prefix
> contig_list.tmp
echo $csv | tr "," "\n" | \
while read bin; do
fasta=${prefix}/${prefix}.${bin}.fa
grep "^>" $fasta | sed 's/^>//' >> contig_list.tmp
grep -Ff contig_list.tmp ${prefix}/${prefix}.metabat2.depth.txt | \
awk -F "\t" '{print $3}' | \
sort -nr \
> depth_list.tmp
done
echo $prefix >> $outfile
head -n 1 depth_list.tmp >> $outfile
tail -n 1 depth_list.tmp >> $outfile
done
rm *tmp

##Combine the bins for each MAG.
cd ~/data/assembly_workflow/metabat2_out/final_MAGs/second_assemblies
cat ~/data/assembly_workflow/metabat2_out/second_assemblies/TazBins.tsv | \
while read prefix csv; do
outfile=${prefix}_final_MAG.fa 
> $outfile 
echo $csv | tr "," "\n" | \
while read bin; do
cat ../../second_assemblies/${prefix}/${prefix}.${bin}.fa >> $outfile
done
cat $outfile | \
awk ' {if ($0 ~ "^>") {printf "\n"$0"\n"} else { printf $0} }; END {printf "\n"} ' | \
tail -n +2 \
> tmp
mv tmp $outfile
done

##Add the unbinned contigs with mmseqs taxonomy support > 0.950 to their respective bins
cd ~/data/assembly_workflow/metabat2_out/second_assemblies
contig_tsv=~/data/assembly_workflow/mmseqs2_out/second_assemblies/all_contigs/taxonomyResult.sorted.unbinned.Taz.tsv
awk -F "\t" '{print $1}' $contig_tsv > contigs2add.list
contig_list=contigs2add.list
cat ~/Li.prefix.list | \
while read prefix; do
grep "^${prefix}" $contig_list | \
sed "s/^${prefix}_/>/" \
> headers.tmp
grep --no-group-separator -A 1 -Ff headers.tmp ${prefix}/${prefix}.unbinned.fa >> ../final_MAGs/second_assemblies/${prefix}_final_MAG.fa
done
rm *.tmp
